services:
  mongo-db:
    image: mongo:8.0.10
    container_name: mongo-db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATASOURCE_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DATASOURCE_PASSWORD}
    volumes:
      - ./mongo:/data/db
  postgres-db:
    image: postgres:17.5
    container_name: postgres-db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${DATASOURCE_DB}
      - POSTGRES_USER=${DATASOURCE_USER}
      - POSTGRES_PASSWORD=${DATASOURCE_PASSWORD}
    volumes:
      - ./postgres:/var/lib/postgresql/data
